spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/gatewayjwt
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platfrom: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
    instance:
      hostname: localhost

server:
  port: 9087

